# Generated by Django 5.2.3 on 2025-07-18 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WearableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=100)),
                ('heart_rate', models.IntegerField(null=True)),
                ('steps', models.IntegerField(null=True)),
                ('temperature', models.FloatField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('battery_level', models.IntegerField(null=True)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
