# Generated by Django 5.1.7 on 2025-05-30 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_safe_field_removal'),
    ]

    operations = [
        # This is a no-op migration to fix the migration state
        # The fields that were supposed to be removed don't exist in the current database
        # so we just mark this migration as applied without doing anything
    ]
