# Generated by Django 5.2.3 on 2025-07-14 18:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_fix_userprofile_state'),
        ('users', '0003_user_google_id_user_profile_picture_url'),
    ]

    operations = [
    ]
